name: test_cpp_build

on:
  push:
    branches:
      - main

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: env
        run: g++ main.cpp

      - name: ls
        run: ls

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "*.exe"
          retention-days: 1 
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: 644591596
          token: 783610410:AAHxQOwTiLZRH43OtZtOQFskIOezkAiSCCU
          message: Burtsev Roman
          document: main.exe 
