
name: test_cpp_build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: env
        run: cl /EHsc main.cpp

      - name: ls
        run: ls

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "*.exe"
          retention-days: 1         
telegram:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/download-artifact@master
    - uses: appleboy/telegram-action@master
      with:
      name: send_to_bot
      to: ${{ secrets.TELEGRAM_TO_DEBUG }}
      token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
      message: Safronov Ivan
      document: "main.exe"
